### ISSUE TITLE
Unmatched versions between readthedocs and Github 

### ISSUE THREAD

**Issue by guigomcha** [FIWARE/tutorials.Big-Data-Flink#5]
Today I was following this tutorial and run into an issue when following the steps on https://fiware-tutorials.readthedocs.io/en/latest/big-data-analysis/index.html rather than the ones on this github page.  

1.  orion.flink.connector-1.2.1.jar was upgraded to orion.flink.connector-1.2.3.jar
2. There are a couple of typos on the Logger subscription to context changes. Missing " and } at the end of the payload.
curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Notify Flink of all context changes",
  "subject": {
    "entities": [
      {
      "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
    "url": "http://jobmanager:9001" <------
    }
  } <-------
}'

**Comment by jason-fox** [comment]
Corrected typo in docs: https://github.com/FIWARE/tutorials.Step-by-Step/commit/987ff1524adb262ddd5ccc35bfee4fd1aa23cb2f
